title: Getting Git  
author: Dez Adkins
email: desmondadkins@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dez Adkins's first GitHub page. Learning how to use this platform for better
  success in the future.
theme: minima

# social links
twitter_username: desmondadkins # DO NOT include the @ character, or else the build will fail!
github_username:  dezadkins # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
